import type { PlayerPreset } from "../types"

export const playerPresets: PlayerPreset[] = [
  {
    sprite: "dwarf",
    name: "Krom",
    genre: "male",
    points: 1,
    movement: 8,
    actions: 2,
    attack: 3,
    defence: 2,
    aim: 0,
    magic: 0,
    health: 8,
    maxHealth: 8,
  },
  {
    sprite: "bandit",
    name: "Elerin",
    genre: "female",
    points: 1,
    movement: 8,
    actions: 2,
    attack: 1,
    defence: 2,
    aim: 2,
    magic: 0,
    health: 8,
    maxHealth: 8,
  },
  {
    sprite: "warlock",
    name: "Vellja",
    genre: "female",
    points: 1,
    movement: 8,
    actions: 2,
    attack: 2,
    defence: 1,
    aim: 0,
    magic: 2,
    health: 8,
    maxHealth: 8,
  },
  {
    sprite: "knight",
    name: "Macroc",
    genre: "male",
    points: 1,
    movement: 6,
    actions: 2,
    attack: 4,
    defence: 3,
    aim: 0,
    magic: 0,
    health: 8,
    maxHealth: 8,
  },
  {
    sprite: "shield knight",
    name: "Adelbald",
    genre: "male",
    points: 1,
    movement: 6,
    actions: 2,
    attack: 2,
    defence: 5,
    aim: 0,
    magic: 0,
    health: 8,
    maxHealth: 8,
  },
  {
    sprite: "monk",
    name: "Don Don",
    genre: "male",
    points: 1,
    movement: 8,
    actions: 2,
    attack: 1,
    defence: 1,
    aim: 0,
    magic: 3,
    health: 8,
    maxHealth: 8,
  },
  {
    sprite: "female winter barbarian",
    name: "Merinya",
    genre: "female",
    points: 1,
    movement: 8,
    actions: 2,
    attack: 3,
    defence: 2,
    aim: 0,
    magic: 0,
    health: 8,
    maxHealth: 8,
  },
  {
    sprite: "female wizard",
    name: "Rizad",
    genre: "female",
    points: 1,
    movement: 8,
    actions: 2,
    attack: 1,
    defence: 1,
    aim: 0,
    magic: 3,
    health: 8,
    maxHealth: 8,
  },
]
